services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/JosueFrnco/Esp32Mongo.git
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://jochue:Dragon104@cluster0.4du6j.mongodb.net/BasePryEsp32?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"