services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/JosueFrnco/Esp32Mongo.git
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://josue:dragon104@cluster0.rah5cdu.mongodb.net/BasePryEsp32?retryWrites=true&w=majority
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
